### ISSUE TITLE
使用 Cypress 测试小程序的探索

### ISSUE THREAD

**Issue by rankun203** [BinZhiZhu/Taro-v2ex-weapp#12]
Hello，BinZhiZhu

我看到你在项目里添加了 Cypress，但还没开始写具体的测试，好奇你成功将 Cypress 集成进来了么？

除此之外，小程序 / Taro.js 还有什么好的集成测试方案么？

**Comment by BinZhiZhu** [comment]
> Hello，BinZhiZhu
> 
> 我看到你在项目里添加了 Cypress，但还没开始写具体的测试，好奇你成功将 Cypress 集成进来了么？
> 
> 除此之外，小程序 / Taro.js 还有什么好的集成测试方案么？

Hello,rankun203。你好，cypress当初是想单独维护H5版本，因为cypress在web应用可以很灵活，可以编写一些e2e的测试用例来确保业务是正常。如果是针对微信小程序的一些自动化测试、e2e测试，我其实是没有实践过，但是我有了解过一些，希望可以对你有参考价值：

微信官方推荐的自动化：

https://developers.weixin.qq.com/miniprogram/dev/devtools/auto/quick-start.html

另外就是腾讯开源的FAutoTest

https://github.com/Tencent/FAutoTest

**Comment by rankun203** [comment]
@BinZhiZhu Nice, thanks man
